### ISSUE TITLE
Feature req: modify ssh port

### ISSUE THREAD

**Issue by jansepke** [linuxserver/docker-openssh-server#30] opened 2020-12-15 10:51 UTC
I want to use this container as a temporary bastion host on AWS. I want to deploy it on AWS ECS Fargate where it is not possible to map container ports.

Could you add an option (env variable) to override the default SSH port, so one can connect on a different port? e.g. SSH_PORT=2223

**Comment by cwong-openfit** [comment] 2021-12-27 18:13
hmm. i have the same issue. i set the port to 2223 but the issue is the script is hardcoded to 2222

**Comment by thespad** [comment] 2021-12-27 18:46
There's an open PR (https://github.com/linuxserver/docker-openssh-server/pull/42) but it's waiting on the submitter to make the necessary documentation changes.

I think they got bored.

**Comment by cwong-openfit** [comment] 2021-12-27 19:16
thank you! :D

**Comment by LDAP** [comment] 2021-12-28 13:19
Until #42 is merged, this is my workaround:

Create a file `custom-port.sh` in `<config-path>/custom-cont-init.d/` with:
```bash
#!/bin/bash

# Replace 22 with your custom port
sed -i 's/-p 2222/-p 22/' /etc/services.d/openssh-server/run
```

**Comment by cwong-openfit** [comment] 2021-12-28 15:36
ya. i did the same last eve.

```
sed -i -e 's/^USER_NAME=.*/USER_NAME=root/' -e 's/2222$/22/' /etc/services.d/openssh-server/run
```
i had to change the `USER_NAME=root` because i was getting perm denied as the regular user (911).
which i also had to change the perm and ownership of the ssh_host* files as well.

**Comment by andryyy** [comment] 2023-01-14 09:33
Doing it like this rn in a custom init script:

```
sed -i 's/2222/{{ env "NOMAD_PORT_[[ $task.name ]]" }}/' /etc/s6-overlay/s6-rc.d/svc-openssh-server/run
sed -i 's/2222/{{ env "NOMAD_PORT_[[ $task.name ]]" }}/' /var/run/service/svc-openssh-server/run.user
```

Feels dirty.

Another approach is to run socat:

```
socat TCP-LISTEN:{{ env "NOMAD_PORT_[[ $task.name ]]" }},fork,reuseaddr TCP:127.0.0.1:2222 &
```

One should consider putting that in a loop, I guess (getting dirty again):

```
(
while true; do
  socat TCP-LISTEN:{{ env "NOMAD_PORT_[[ $task.name ]]" }},fork,reuseaddr TCP:127.0.0.1:2222
done
) &
```

**Comment by koraa** [comment] 2023-04-11 11:39
bump. This is still highly desired. Not having a port config option in a server ist just silly for anything but the simplest servers.

**Comment by linuxmaniac** [comment] 2023-04-27 08:25
https://github.com/linuxserver/docker-openssh-server/blob/6ebd6fe00ac17c9930247927f8e7522aa68c280f/root/etc/s6-overlay/s6-rc.d/init-openssh-server-config/run#L44-L53

It seems you can just use ``LISTEN_PORT``

**Comment by yoelvd** [comment] 2023-05-06 21:10
Ok I added LISTEN_PORT as a new environment variable for my docker-compose and it works! And yet, the corresponding image documentation isn't reflecting this change. I had to come here to learn this. Thanks @linuxmaniac

**Comment by linuxmaniac** [comment] 2023-05-08 08:29
@yoelvd please provide a PR with the changes in doc that you would like to see as a new user of the image. That would be great

**Comment by thespad** [comment] 2023-05-08 10:18
It's not documented because we don't support it.

95% of the use cases that require it are scenarios we don't support in the first place because they are entirely ephemeral and don't provide any means of mounting a persistent /config (and thus editing `sshd_config` to change the listen port). Including it in the readme would imply support that we're not willing to provide.

Rather than not provide any option at all, we opted to provide an undocumented route that those with the wherewithal to understand can make use of, on the basis that if you can figure that out you're probably not going to be coming back to us for basic support for your weird setup.

(And yes, we were originally hard-coding the listen port in the sshd run command which was overriding the value(s) in `sshd_config` but that's no longer the case).

**Comment by drizuid** [comment] 2023-05-08 11:23
closing as we have provided an explanation and our support stance. We will not entertain documenting it.

**Closed as completed by drizuid** 2023-05-08 11:23 UTC
